name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  windows:
    name: Windows
    runs-on: windows-2022
    timeout-minutes: 60
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install deps
        env:
          npm_config_foreground_scripts: "true"
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        run: npm install

      - name: Make
        run: npm run make

      - name: List files
        run: |
          ls out
          ls out/make
          ls out/make/zip
          ls out/make/zip/win32
          ls out/make/zip/win32/x64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: out/make/zip/win32/x64/cirina-win32-x64-*.zip

  linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install deps
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        run: npm install

      - name: Make
        run: npm run make

      - name: List files
        run: |
          ls -alh out
          ls -alh out/make
          ls -alh out/make/zip
          ls -alh out/make/zip/linux
          ls -alh out/make/zip/linux/x64
          ls -alh out/cirina-linux-x64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: out/make/zip/linux/x64/cirina-linux-x64-*.zip

  darwin:
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Install deps
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
        run: npm install

      - name: Make
        run: npm run make

      - name: List files
        run: |
          ls -alh out/make/*
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin
          path: out/make/cirina-*-arm64.dmg

  release:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [windows, linux, darwin]
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: darwin

      - name: List files
        run: |
          ls -R

      - name: Release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG
          files: |
            cirina-${{ github.ref_name }}-arm64.dmg
            cirina-linux-x64-${{ github.ref_name }}.zip
            cirina-win32-x64-${{ github.ref_name }}.zip
